// Build-time bundler for the legal documents.
//
// The source of truth is Markdown in src/content/legal/<locale>/<slug>.md —
// that is the format the documents are drafted and reviewed in. This script
// inlines them into a TypeScript module so pages import strings instead of
// reading the filesystem, which the Cloudflare Workers runtime does not have.
//
// Run: npm run generate:legal (also runs automatically before `next build`).

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = join(root, 'src/content/legal');
const locales = ['pl', 'en', 'es', 'de'];

const documents = {};
for (const locale of locales) {
  documents[locale] = {};
  const files = readdirSync(join(contentDir, locale))
    .filter((name) => name.endsWith('.md'))
    .sort();
  for (const file of files) {
    const slug = file.replace(/\.md$/, '');
    documents[locale][slug] = readFileSync(join(contentDir, locale, file), 'utf8');
  }
}

const slugs = Object.keys(documents[locales[0]]);
for (const locale of locales.slice(1)) {
  const missing = slugs.filter((slug) => !documents[locale][slug]);
  if (missing.length) {
    throw new Error(`Missing ${locale} translation for: ${missing.join(', ')}`);
  }
}

const outDir = join(root, 'src/generated');
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, 'legal.ts'),
  '// AUTO-GENERATED by scripts/generate-legal.mjs — do not edit by hand.\n' +
    '// Edit the Markdown in src/content/legal/ and regenerate with:\n' +
    '//   npm run generate:legal\n\n' +
    `export type LegalSlug = ${slugs.map((slug) => `'${slug}'`).join(' | ')};\n\n` +
    `export const legalDocuments: Record<'pl' | 'en' | 'es' | 'de', Record<LegalSlug, string>> = ${JSON.stringify(
      documents,
      null,
      2,
    )};\n`,
);

console.log(`Bundled ${slugs.length} legal documents in ${locales.length} locales`);
