// Build-time generator for country map silhouettes (entry landing) and
// country-shaped flags (For Developers page).
//
// Source of truth: design_handoff README — geometry comes from real
// geographic data (world-atlas@2.0.2, 50m resolution, vendored in
// vendor/world-atlas/countries-50m.json). Never hand-drawn paths.
//
// Output: src/generated/maps.ts and src/generated/flags.ts — plain SVG
// markup strings rendered inline by server components, so the browser
// never downloads TopoJSON or d3 at runtime.
//
// Run: npm run generate:geo (also runs automatically before `next build`).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { geoMercator, geoPath, geoArea, geoCentroid } from 'd3-geo';
import { feature } from 'topojson-client';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const topo = JSON.parse(
  readFileSync(join(root, 'vendor/world-atlas/countries-50m.json'), 'utf8'),
);
const countries = feature(topo, topo.objects.countries).features;

// Overseas-territory filter (required): for MultiPolygon features keep the
// largest polygon, then only polygons that are >=2% of the largest area AND
// whose centroid lies within 8 degrees of the main polygon's centroid.
// Without this, the Azores, Madeira and the Canaries force Spain and
// Portugal to render as tiny specks.
function mainlandGeometry(f) {
  if (f.geometry.type !== 'MultiPolygon') return f;
  const polys = f.geometry.coordinates.map((coords) => ({
    coords,
    a: geoArea({ type: 'Polygon', coordinates: coords }),
  }));
  const max = Math.max(...polys.map((p) => p.a));
  const main = polys.find((p) => p.a === max).coords;
  const c0 = geoCentroid({ type: 'Polygon', coordinates: main });
  const near = polys
    .filter((p) => {
      if (p.a < max * 0.02) return false;
      const c1 = geoCentroid({ type: 'Polygon', coordinates: p.coords });
      return Math.hypot(c1[0] - c0[0], c1[1] - c0[1]) < 8;
    })
    .map((p) => p.coords);
  return {
    type: 'Feature',
    geometry: { type: 'MultiPolygon', coordinates: near.length ? near : [main] },
  };
}

function featureById(id) {
  const f = countries.find((c) => c.id === id);
  if (!f) throw new Error(`Country id ${id} not found in world-atlas data`);
  return f;
}

const banner =
  '// AUTO-GENERATED by scripts/generate-geo.mjs — do not edit by hand.\n' +
  '// Regenerate with: npm run generate:geo\n';

// ---------------------------------------------------------------------------
// Entry-landing map silhouettes
// ---------------------------------------------------------------------------

const MAPS = [
  { key: 'cyp', id: '196', active: true },
  { key: 'esp', id: '724' },
  { key: 'prt', id: '620' },
  { key: 'ita', id: '380' },
];

function mapSvg({ key, id, active }) {
  const W = 260;
  const H = 150;
  const geom = mainlandGeometry(featureById(id));
  const proj = geoMercator().fitExtent(
    [
      [10, 10],
      [W - 10, H - 10],
    ],
    geom,
  );
  const d = geoPath(proj)(geom);
  const gradId = `map-grad-${key}`;
  const defs = active
    ? `<defs><linearGradient id="${gradId}" x1="0" y1="0" x2="0.35" y2="1">` +
      `<stop offset="0" stop-color="#3FA593"/>` +
      `<stop offset="0.45" stop-color="#1F8375"/>` +
      `<stop offset="1" stop-color="#125A50"/>` +
      `</linearGradient></defs>`
    : '';
  const fill = active ? `url(#${gradId})` : '#E4E2DC';
  const stroke = active ? '#125A50' : '#CFCDC6';
  return (
    `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">` +
    defs +
    `<path d="${d}" fill="${fill}" stroke="${stroke}" stroke-width="1" stroke-linejoin="round"/>` +
    `</svg>`
  );
}

const maps = Object.fromEntries(MAPS.map((m) => [m.key, mapSvg(m)]));

// ---------------------------------------------------------------------------
// Country-shaped flags (investor-sources band)
// ---------------------------------------------------------------------------

const FLAG_IDS = { pl: '616', de: '276', cz: '203', hu: '348', lt: '440', ro: '642' };
const STRIPES = {
  // horizontal: colors top->bottom; vertical: colors left->right; cz special
  pl: { dir: 'h', colors: ['#FFFFFF', '#DC143C'] },
  de: { dir: 'h', colors: ['#1A1A1A', '#DD0000', '#FFCE00'] },
  cz: { dir: 'cz' },
  hu: { dir: 'h', colors: ['#CE2939', '#FFFFFF', '#477050'] },
  lt: { dir: 'h', colors: ['#FDB913', '#006A44', '#C1272D'] },
  ro: { dir: 'v', colors: ['#002B7F', '#FCD116', '#CE1126'] },
};
const ACTIVE_FLAGS = new Set(['pl']);

function stripes(code, W, H) {
  const s = STRIPES[code];
  if (s.dir === 'cz') {
    return (
      `<rect width="${W}" height="${H / 2}" fill="#FFFFFF"/>` +
      `<rect y="${H / 2}" width="${W}" height="${H / 2}" fill="#D7141A"/>` +
      `<path d="M0 0 L${W * 0.5} ${H / 2} L0 ${H} Z" fill="#11457E"/>`
    );
  }
  const n = s.colors.length;
  return s.colors
    .map((c, i) =>
      s.dir === 'h'
        ? `<rect y="${(H / n) * i}" width="${W}" height="${H / n + 0.6}" fill="${c}"/>`
        : `<rect x="${(W / n) * i}" width="${W / n + 0.6}" height="${H}" fill="${c}"/>`,
    )
    .join('');
}

function flagSvg(code) {
  const W = 180;
  const H = 132;
  const uid = `flag-${code}`;
  const geom = mainlandGeometry(featureById(FLAG_IDS[code]));
  const proj = geoMercator().fitExtent(
    [
      [6, 6],
      [W - 6, H - 6],
    ],
    geom,
  );
  const d = geoPath(proj)(geom);
  const stroke = ACTIVE_FLAGS.has(code) ? '#1F8375' : '#98A19E';
  return (
    `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">` +
    `<defs>` +
    `<clipPath id="clip-${uid}"><path d="${d}"/></clipPath>` +
    `<linearGradient id="sheen-${uid}" x1="0" y1="0" x2="0.9" y2="1">` +
    `<stop offset="0" stop-color="#fff" stop-opacity="0.34"/>` +
    `<stop offset="0.35" stop-color="#fff" stop-opacity="0.02"/>` +
    `<stop offset="0.62" stop-color="#000" stop-opacity="0.10"/>` +
    `<stop offset="0.85" stop-color="#fff" stop-opacity="0.16"/>` +
    `<stop offset="1" stop-color="#000" stop-opacity="0.06"/>` +
    `</linearGradient>` +
    `<filter id="drop-${uid}" x="-25%" y="-25%" width="150%" height="150%">` +
    `<feDropShadow dx="0" dy="3" stdDeviation="3.4" flood-color="#101614" flood-opacity="0.26"/>` +
    `</filter>` +
    `</defs>` +
    `<g filter="url(#drop-${uid})">` +
    `<g clip-path="url(#clip-${uid})">` +
    stripes(code, W, H) +
    `<rect width="${W}" height="${H}" fill="url(#sheen-${uid})"/>` +
    `</g>` +
    `<path d="${d}" fill="none" stroke="${stroke}" stroke-width="1.1" stroke-linejoin="round"/>` +
    `</g>` +
    `</svg>`
  );
}

const flags = Object.fromEntries(Object.keys(FLAG_IDS).map((c) => [c, flagSvg(c)]));

// ---------------------------------------------------------------------------

const outDir = join(root, 'src/generated');
mkdirSync(outDir, { recursive: true });

writeFileSync(
  join(outDir, 'maps.ts'),
  `${banner}\nexport const countryMaps: Record<'cyp' | 'esp' | 'prt' | 'ita', string> = ${JSON.stringify(maps, null, 2)};\n`,
);
writeFileSync(
  join(outDir, 'flags.ts'),
  `${banner}\nexport const countryFlags: Record<'pl' | 'de' | 'cz' | 'hu' | 'lt' | 'ro', string> = ${JSON.stringify(flags, null, 2)};\n`,
);

console.log(
  `Generated ${Object.keys(maps).length} maps and ${Object.keys(flags).length} flags in src/generated/`,
);
